export const ActionConstants = {
  Meals: {
    GetMealsInit: "GET_MEALS_INIT",
    GetMealsSuccess: "GET_MEALS_SUCCESS",
    GetMealsFail: "GET_MEALS_FAIL",
    AddMealInit: "ADD_MEAL_INIT",
    AddMealSuccess: "ADD_MEAL_SUCCESS",
    AddMealFail: "ADD_MEAL_FAIL",
    DeleteMealInit: "DELETE_MEAL_INIT",
    DeleteMealSuccess: "DELETE_MEAL_SUCCESS",
    DeleteMealFail: "DELETE_MEAL_FAIL",
    ModifyMealInit: "MODIFY_MEAL_INIT",
    ModifyMealSuccess: "MODIFY_MEAL_SUCCESS",
    ModifyMealFail: "MODIFY_MEAL_FAIL",
    MealsReset: "MEALS_RESET",
  },
  Labels: {
    GetLabelsInit: "GET_LABELS_INIT",
    GetLabelsSuccess: "GET_LABELS_SUCCESS",
    GetLabelsFail: "GET_LABELS_FAIL",
    LabelsReset: "LABELS_RESET",
  },
  Orders: {
    PlaceOrderInit: "PLACE_ORDER_INIT",
    PlaceOrderSuccess: "PLACE_ORDER_SUCCESS",
    PlaceOrderFail: "PLACE_ORDER_FAIL",
    ModifyOrderInit: "MODIFY_ORDER_INIT",
    ModifyOrderSuccess: "MODIFY_ORDER_SUCCESS",
    ModifyOrderFail: "MODIFY_ORDER_FAIL",
  },
};
